[package]
  name = "my-almandine-project"
  version = "0.1.0"
  license = "MIT"

[scripts]
  run = "go run main.go"

[dependencies]
  [dependencies.foo]
    source = "github:Oval-Tutu/shove/shove.lua@main"
    path = "src/lib/foo.lua"
  [dependencies.shove]
    source = "github:Oval-Tutu/shove/shove.lua@81f7f879a812e4479493a88e646831d0f0409560"
    path = "src/lib/shove.lua"
  [dependencies.testname]
    source = "github:Oval-Tutu/shove/shove.lua@81f7f879a812e4479493a88e646831d0f0409560"
    path = "testdir/testname.lua"
