# CI workflow for lint, test, and coverage reporting (Coveralls)
# Runs on all pushes and PRs

name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Test on ${{ matrix.lua-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua-version: [ '5.1', '5.2', '5.3', '5.4', 'luajit' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v11
        with:
          lua-version: ${{ matrix.lua-version }}

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v5

      - name: Install dependencies
        run: |
          luarocks install luacheck
          luarocks install busted
          luarocks install luacov
          luarocks install luacov-coveralls

      - name: Lint source
        run: luacheck src/ || exit 1

      - name: Lint specs
        run: luacheck src/spec/ || exit 1

      - name: Run tests with coverage
        run: busted --coverage src/spec

      - name: Generate coverage report
        run: luacov

      - name: Upload coverage to Coveralls
        if: matrix.lua-version == '5.1'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          luarocks install luacov-coveralls
          luacov-coveralls -v
